2017-07-06 00:01:38,285 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.020) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2017-07-06 00:01:38,401 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.104) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '1496110887352098'; args=('1496110887352098',)
2017-07-06 00:01:38,471 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.027) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2017-07-06 00:01:38,515 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.020) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '1496110887352098'; args=('1496110887352098',)
2017-07-06 00:01:38,542 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.023) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2017-07-06 00:01:38,568 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.021) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '1496110887352098'; args=('1496110887352098',)
2017-07-06 00:01:38,601 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.023) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2017-07-06 00:01:38,661 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.043) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '1496110887352098'; args=('1496110887352098',)
2017-07-06 00:01:38,691 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.024) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2017-07-06 00:01:38,718 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.022) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '1497696573972824'; args=('1497696573972824',)
2017-07-06 00:01:38,745 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.022) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 3; args=(3,)
2017-07-06 00:01:38,771 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.021) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '1497696573972824'; args=('1497696573972824',)
2017-07-06 00:01:38,796 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.021) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 3; args=(3,)
2017-07-06 00:01:38,825 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.023) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '1497696573972824'; args=('1497696573972824',)
2017-07-06 00:01:38,852 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.022) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 3; args=(3,)
2017-07-06 00:01:38,880 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.023) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '1497696573972824'; args=('1497696573972824',)
2017-07-06 00:01:38,919 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.021) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 3; args=(3,)
2017-07-06 00:01:38,956 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.032) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '1497696573972824'; args=('1497696573972824',)
2017-07-06 00:01:39,026 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.066) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 3; args=(3,)
2017-07-06 00:01:39,214 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.142) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '1497696573972824'; args=('1497696573972824',)
2017-07-06 00:01:39,333 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.055) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 3; args=(3,)
2017-07-06 00:01:39,395 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.032) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '1497696573972824'; args=('1497696573972824',)
2017-07-06 00:01:39,434 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.025) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 3; args=(3,)
2017-07-06 00:01:39,512 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.038) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '1497085483006318'; args=('1497085483006318',)
2017-07-06 00:01:39,555 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.032) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2017-07-06 00:01:39,619 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.052) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '14968059463023229'; args=('14968059463023229',)
2017-07-06 00:01:39,648 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.021) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2017-07-06 00:01:39,678 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.022) SELECT `goods`.`id`, `goods`.`user_id`, `goods`.`shop_id`, `goods`.`name`, `goods`.`pgoods_id`, `goods`.`sendaddress`, `goods`.`platform`, `goods`.`image1`, `goods`.`image2`, `goods`.`image3`, `goods`.`keyword1`, `goods`.`price1`, `goods`.`remark1`, `goods`.`keyword2`, `goods`.`price2`, `goods`.`remark2`, `goods`.`keyword3`, `goods`.`price3`, `goods`.`remark3`, `goods`.`keyword4`, `goods`.`price4`, `goods`.`remark4`, `goods`.`keyword5`, `goods`.`price5`, `goods`.`remark5`, `goods`.`add_time` FROM `goods` WHERE `goods`.`id` = '1496110887352098'; args=('1496110887352098',)
2017-07-06 00:01:39,722 [Thread-14:123145440067584] [django.db.backends:90] [utils:execute] [DEBUG]- (0.037) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `auth_user`.`is_seller`, `auth_user`.`is_blacklist`, `auth_user`.`address`, `auth_user`.`mobile`, `auth_user`.`balance`, `auth_user`.`wechatName`, `auth_user`.`wechat`, `auth_user`.`qq`, `auth_user`.`alipay`, `auth_user`.`bankName`, `auth_user`.`bankID`, `auth_user`.`realname`, `auth_user`.`tags`, `auth_user`.`image`, `auth_user`.`referrercode`, `auth_user`.`remark` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2017-07-06 00:01:39,744 [Thread-14:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'orderslists' in template 'material/manager/table.html'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'orderslists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'orderslists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'orderslists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: <unprintable VariableDoesNotExist object>
2017-07-06 00:01:39,746 [Thread-14:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'orderslists' in template 'material/manager/table.html'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'orderslists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'orderslists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'orderslists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: <unprintable VariableDoesNotExist object>
2017-07-06 00:01:39,748 [Thread-14:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'orderslists' in template 'material/manager/table.html'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'orderslists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'orderslists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'orderslists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: <unprintable VariableDoesNotExist object>
2017-07-06 00:01:39,750 [Thread-14:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'orderslists' in template 'material/manager/table.html'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'orderslists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'orderslists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'orderslists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: <unprintable VariableDoesNotExist object>
2017-07-06 00:01:39,760 [Thread-14:123145440067584] [django.server:131] [basehttp:log_message] [INFO]- "GET /users/manage/ HTTP/1.1" 200 80035
2017-07-06 00:01:41,067 [Thread-15:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <module 'grappelli.urls' from '/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/grappelli/urls.py'> (None:None) ^grappelli/>], [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'blacklist.urls' from '/Users/VANXV/PycharmProjects/zss/blacklist/urls.py'> (None:blacklist) ^blacklist/>], [<RegexURLResolver <module 'goods.urls' from '/Users/VANXV/PycharmProjects/zss/goods/urls.py'> (None:good) ^good/>], [<RegexURLResolver <module 'orders.urls' from '/Users/VANXV/PycharmProjects/zss/orders/urls.py'> (None:order) ^order/>], [<RegexURLResolver <module 'crm.urls' from '/Users/VANXV/PycharmProjects/zss/crm/urls.py'> (None:crm) ^crm/>], [<RegexURLResolver <module 'finance.urls' from '/Users/VANXV/PycharmProjects/zss/finance/urls.py'> (None:finance) ^finance/>], [<RegexURLResolver <module 'cashback.urls' from '/Users/VANXV/PycharmProjects/zss/cashback/urls.py'> (None:cashback) ^cashback/>], [<RegexURLResolver <module 'cryapp.urls' from '/Users/VANXV/PycharmProjects/zss/cryapp/urls.py'> (None:cryapp) ^cryapp/>], [<RegexURLResolver <module 'wechat.urls' from '/Users/VANXV/PycharmProjects/zss/wechat/urls.py'> (None:wechat) m/>], [<RegexURLPattern login ^login/>], [<RegexURLPattern register ^register/>], [<RegexURLPattern logout ^logout/>], [<RegexURLPattern welcome ^welcome/$>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern PcHardwareInsert ^PcHardwareInsert/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ip ^ip/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^tb/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^jd/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/hardware/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdone ^manage/get/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statussix/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statusseven/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdelete ^manage/delete/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersedit ^manage/edit/(?P<cryorders_id>\d+)/$>], [<RegexURLPattern GetGoods ^goods/(?P<goodid>(\d+))>], [<RegexURLPattern webbrowser webbrowser/>], [<RegexURLResolver <module 'financial.urls' from '/Users/VANXV/PycharmProjects/zss/financial/urls.py'> (None:financialurl) ^financial/>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'servers.urls' from '/Users/VANXV/PycharmProjects/zss/servers/urls.py'> (None:None) ^servers/>], [<RegexURLPattern None ^media\/(?P<path>.*)$>]], 'path': 'users/assets/img/sidebar-1.jpg'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'grappelli.urls' from '/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/grappelli/urls.py'> (None:None) ^grappelli/>"
2017-07-06 00:01:41,072 [Thread-15:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <module 'grappelli.urls' from '/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/grappelli/urls.py'> (None:None) ^grappelli/>], [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'blacklist.urls' from '/Users/VANXV/PycharmProjects/zss/blacklist/urls.py'> (None:blacklist) ^blacklist/>], [<RegexURLResolver <module 'goods.urls' from '/Users/VANXV/PycharmProjects/zss/goods/urls.py'> (None:good) ^good/>], [<RegexURLResolver <module 'orders.urls' from '/Users/VANXV/PycharmProjects/zss/orders/urls.py'> (None:order) ^order/>], [<RegexURLResolver <module 'crm.urls' from '/Users/VANXV/PycharmProjects/zss/crm/urls.py'> (None:crm) ^crm/>], [<RegexURLResolver <module 'finance.urls' from '/Users/VANXV/PycharmProjects/zss/finance/urls.py'> (None:finance) ^finance/>], [<RegexURLResolver <module 'cashback.urls' from '/Users/VANXV/PycharmProjects/zss/cashback/urls.py'> (None:cashback) ^cashback/>], [<RegexURLResolver <module 'cryapp.urls' from '/Users/VANXV/PycharmProjects/zss/cryapp/urls.py'> (None:cryapp) ^cryapp/>], [<RegexURLResolver <module 'wechat.urls' from '/Users/VANXV/PycharmProjects/zss/wechat/urls.py'> (None:wechat) m/>], [<RegexURLPattern login ^login/>], [<RegexURLPattern register ^register/>], [<RegexURLPattern logout ^logout/>], [<RegexURLPattern welcome ^welcome/$>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern PcHardwareInsert ^PcHardwareInsert/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ip ^ip/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^tb/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^jd/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/hardware/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdone ^manage/get/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statussix/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statusseven/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdelete ^manage/delete/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersedit ^manage/edit/(?P<cryorders_id>\d+)/$>], [<RegexURLPattern GetGoods ^goods/(?P<goodid>(\d+))>], [<RegexURLPattern webbrowser webbrowser/>], [<RegexURLResolver <module 'financial.urls' from '/Users/VANXV/PycharmProjects/zss/financial/urls.py'> (None:financialurl) ^financial/>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'servers.urls' from '/Users/VANXV/PycharmProjects/zss/servers/urls.py'> (None:None) ^servers/>], [<RegexURLPattern None ^media\/(?P<path>.*)$>]], 'path': 'users/assets/img/sidebar-1.jpg'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
2017-07-06 00:01:41,077 [Thread-15:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <module 'grappelli.urls' from '/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/grappelli/urls.py'> (None:None) ^grappelli/>], [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'blacklist.urls' from '/Users/VANXV/PycharmProjects/zss/blacklist/urls.py'> (None:blacklist) ^blacklist/>], [<RegexURLResolver <module 'goods.urls' from '/Users/VANXV/PycharmProjects/zss/goods/urls.py'> (None:good) ^good/>], [<RegexURLResolver <module 'orders.urls' from '/Users/VANXV/PycharmProjects/zss/orders/urls.py'> (None:order) ^order/>], [<RegexURLResolver <module 'crm.urls' from '/Users/VANXV/PycharmProjects/zss/crm/urls.py'> (None:crm) ^crm/>], [<RegexURLResolver <module 'finance.urls' from '/Users/VANXV/PycharmProjects/zss/finance/urls.py'> (None:finance) ^finance/>], [<RegexURLResolver <module 'cashback.urls' from '/Users/VANXV/PycharmProjects/zss/cashback/urls.py'> (None:cashback) ^cashback/>], [<RegexURLResolver <module 'cryapp.urls' from '/Users/VANXV/PycharmProjects/zss/cryapp/urls.py'> (None:cryapp) ^cryapp/>], [<RegexURLResolver <module 'wechat.urls' from '/Users/VANXV/PycharmProjects/zss/wechat/urls.py'> (None:wechat) m/>], [<RegexURLPattern login ^login/>], [<RegexURLPattern register ^register/>], [<RegexURLPattern logout ^logout/>], [<RegexURLPattern welcome ^welcome/$>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern PcHardwareInsert ^PcHardwareInsert/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ip ^ip/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^tb/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^jd/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/hardware/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdone ^manage/get/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statussix/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statusseven/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdelete ^manage/delete/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersedit ^manage/edit/(?P<cryorders_id>\d+)/$>], [<RegexURLPattern GetGoods ^goods/(?P<goodid>(\d+))>], [<RegexURLPattern webbrowser webbrowser/>], [<RegexURLResolver <module 'financial.urls' from '/Users/VANXV/PycharmProjects/zss/financial/urls.py'> (None:financialurl) ^financial/>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'servers.urls' from '/Users/VANXV/PycharmProjects/zss/servers/urls.py'> (None:None) ^servers/>], [<RegexURLPattern None ^media\/(?P<path>.*)$>]], 'path': 'users/assets/img/sidebar-1.jpg'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'blacklist.urls' from '/Users/VANXV/PycharmProjects/zss/blacklist/urls.py'> (None:blacklist) ^blacklist/>"
2017-07-06 00:01:41,084 [Thread-15:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <module 'grappelli.urls' from '/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/grappelli/urls.py'> (None:None) ^grappelli/>], [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'blacklist.urls' from '/Users/VANXV/PycharmProjects/zss/blacklist/urls.py'> (None:blacklist) ^blacklist/>], [<RegexURLResolver <module 'goods.urls' from '/Users/VANXV/PycharmProjects/zss/goods/urls.py'> (None:good) ^good/>], [<RegexURLResolver <module 'orders.urls' from '/Users/VANXV/PycharmProjects/zss/orders/urls.py'> (None:order) ^order/>], [<RegexURLResolver <module 'crm.urls' from '/Users/VANXV/PycharmProjects/zss/crm/urls.py'> (None:crm) ^crm/>], [<RegexURLResolver <module 'finance.urls' from '/Users/VANXV/PycharmProjects/zss/finance/urls.py'> (None:finance) ^finance/>], [<RegexURLResolver <module 'cashback.urls' from '/Users/VANXV/PycharmProjects/zss/cashback/urls.py'> (None:cashback) ^cashback/>], [<RegexURLResolver <module 'cryapp.urls' from '/Users/VANXV/PycharmProjects/zss/cryapp/urls.py'> (None:cryapp) ^cryapp/>], [<RegexURLResolver <module 'wechat.urls' from '/Users/VANXV/PycharmProjects/zss/wechat/urls.py'> (None:wechat) m/>], [<RegexURLPattern login ^login/>], [<RegexURLPattern register ^register/>], [<RegexURLPattern logout ^logout/>], [<RegexURLPattern welcome ^welcome/$>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern PcHardwareInsert ^PcHardwareInsert/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ip ^ip/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^tb/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^jd/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/hardware/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdone ^manage/get/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statussix/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statusseven/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdelete ^manage/delete/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersedit ^manage/edit/(?P<cryorders_id>\d+)/$>], [<RegexURLPattern GetGoods ^goods/(?P<goodid>(\d+))>], [<RegexURLPattern webbrowser webbrowser/>], [<RegexURLResolver <module 'financial.urls' from '/Users/VANXV/PycharmProjects/zss/financial/urls.py'> (None:financialurl) ^financial/>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'servers.urls' from '/Users/VANXV/PycharmProjects/zss/servers/urls.py'> (None:None) ^servers/>], [<RegexURLPattern None ^media\/(?P<path>.*)$>]], 'path': 'users/assets/img/sidebar-1.jpg'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'goods.urls' from '/Users/VANXV/PycharmProjects/zss/goods/urls.py'> (None:good) ^good/>"
2017-07-06 00:01:41,089 [Thread-15:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <module 'grappelli.urls' from '/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/grappelli/urls.py'> (None:None) ^grappelli/>], [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'blacklist.urls' from '/Users/VANXV/PycharmProjects/zss/blacklist/urls.py'> (None:blacklist) ^blacklist/>], [<RegexURLResolver <module 'goods.urls' from '/Users/VANXV/PycharmProjects/zss/goods/urls.py'> (None:good) ^good/>], [<RegexURLResolver <module 'orders.urls' from '/Users/VANXV/PycharmProjects/zss/orders/urls.py'> (None:order) ^order/>], [<RegexURLResolver <module 'crm.urls' from '/Users/VANXV/PycharmProjects/zss/crm/urls.py'> (None:crm) ^crm/>], [<RegexURLResolver <module 'finance.urls' from '/Users/VANXV/PycharmProjects/zss/finance/urls.py'> (None:finance) ^finance/>], [<RegexURLResolver <module 'cashback.urls' from '/Users/VANXV/PycharmProjects/zss/cashback/urls.py'> (None:cashback) ^cashback/>], [<RegexURLResolver <module 'cryapp.urls' from '/Users/VANXV/PycharmProjects/zss/cryapp/urls.py'> (None:cryapp) ^cryapp/>], [<RegexURLResolver <module 'wechat.urls' from '/Users/VANXV/PycharmProjects/zss/wechat/urls.py'> (None:wechat) m/>], [<RegexURLPattern login ^login/>], [<RegexURLPattern register ^register/>], [<RegexURLPattern logout ^logout/>], [<RegexURLPattern welcome ^welcome/$>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern PcHardwareInsert ^PcHardwareInsert/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ip ^ip/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^tb/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^jd/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/hardware/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdone ^manage/get/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statussix/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statusseven/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdelete ^manage/delete/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersedit ^manage/edit/(?P<cryorders_id>\d+)/$>], [<RegexURLPattern GetGoods ^goods/(?P<goodid>(\d+))>], [<RegexURLPattern webbrowser webbrowser/>], [<RegexURLResolver <module 'financial.urls' from '/Users/VANXV/PycharmProjects/zss/financial/urls.py'> (None:financialurl) ^financial/>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'servers.urls' from '/Users/VANXV/PycharmProjects/zss/servers/urls.py'> (None:None) ^servers/>], [<RegexURLPattern None ^media\/(?P<path>.*)$>]], 'path': 'users/assets/img/sidebar-1.jpg'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'orders.urls' from '/Users/VANXV/PycharmProjects/zss/orders/urls.py'> (None:order) ^order/>"
2017-07-06 00:01:41,098 [Thread-15:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <module 'grappelli.urls' from '/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/grappelli/urls.py'> (None:None) ^grappelli/>], [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'blacklist.urls' from '/Users/VANXV/PycharmProjects/zss/blacklist/urls.py'> (None:blacklist) ^blacklist/>], [<RegexURLResolver <module 'goods.urls' from '/Users/VANXV/PycharmProjects/zss/goods/urls.py'> (None:good) ^good/>], [<RegexURLResolver <module 'orders.urls' from '/Users/VANXV/PycharmProjects/zss/orders/urls.py'> (None:order) ^order/>], [<RegexURLResolver <module 'crm.urls' from '/Users/VANXV/PycharmProjects/zss/crm/urls.py'> (None:crm) ^crm/>], [<RegexURLResolver <module 'finance.urls' from '/Users/VANXV/PycharmProjects/zss/finance/urls.py'> (None:finance) ^finance/>], [<RegexURLResolver <module 'cashback.urls' from '/Users/VANXV/PycharmProjects/zss/cashback/urls.py'> (None:cashback) ^cashback/>], [<RegexURLResolver <module 'cryapp.urls' from '/Users/VANXV/PycharmProjects/zss/cryapp/urls.py'> (None:cryapp) ^cryapp/>], [<RegexURLResolver <module 'wechat.urls' from '/Users/VANXV/PycharmProjects/zss/wechat/urls.py'> (None:wechat) m/>], [<RegexURLPattern login ^login/>], [<RegexURLPattern register ^register/>], [<RegexURLPattern logout ^logout/>], [<RegexURLPattern welcome ^welcome/$>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern PcHardwareInsert ^PcHardwareInsert/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ip ^ip/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^tb/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^jd/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/hardware/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdone ^manage/get/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statussix/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statusseven/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdelete ^manage/delete/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersedit ^manage/edit/(?P<cryorders_id>\d+)/$>], [<RegexURLPattern GetGoods ^goods/(?P<goodid>(\d+))>], [<RegexURLPattern webbrowser webbrowser/>], [<RegexURLResolver <module 'financial.urls' from '/Users/VANXV/PycharmProjects/zss/financial/urls.py'> (None:financialurl) ^financial/>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'servers.urls' from '/Users/VANXV/PycharmProjects/zss/servers/urls.py'> (None:None) ^servers/>], [<RegexURLPattern None ^media\/(?P<path>.*)$>]], 'path': 'users/assets/img/sidebar-1.jpg'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'crm.urls' from '/Users/VANXV/PycharmProjects/zss/crm/urls.py'> (None:crm) ^crm/>"
2017-07-06 00:01:41,103 [Thread-15:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <module 'grappelli.urls' from '/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/grappelli/urls.py'> (None:None) ^grappelli/>], [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'blacklist.urls' from '/Users/VANXV/PycharmProjects/zss/blacklist/urls.py'> (None:blacklist) ^blacklist/>], [<RegexURLResolver <module 'goods.urls' from '/Users/VANXV/PycharmProjects/zss/goods/urls.py'> (None:good) ^good/>], [<RegexURLResolver <module 'orders.urls' from '/Users/VANXV/PycharmProjects/zss/orders/urls.py'> (None:order) ^order/>], [<RegexURLResolver <module 'crm.urls' from '/Users/VANXV/PycharmProjects/zss/crm/urls.py'> (None:crm) ^crm/>], [<RegexURLResolver <module 'finance.urls' from '/Users/VANXV/PycharmProjects/zss/finance/urls.py'> (None:finance) ^finance/>], [<RegexURLResolver <module 'cashback.urls' from '/Users/VANXV/PycharmProjects/zss/cashback/urls.py'> (None:cashback) ^cashback/>], [<RegexURLResolver <module 'cryapp.urls' from '/Users/VANXV/PycharmProjects/zss/cryapp/urls.py'> (None:cryapp) ^cryapp/>], [<RegexURLResolver <module 'wechat.urls' from '/Users/VANXV/PycharmProjects/zss/wechat/urls.py'> (None:wechat) m/>], [<RegexURLPattern login ^login/>], [<RegexURLPattern register ^register/>], [<RegexURLPattern logout ^logout/>], [<RegexURLPattern welcome ^welcome/$>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern PcHardwareInsert ^PcHardwareInsert/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ip ^ip/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^tb/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^jd/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/hardware/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdone ^manage/get/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statussix/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statusseven/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdelete ^manage/delete/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersedit ^manage/edit/(?P<cryorders_id>\d+)/$>], [<RegexURLPattern GetGoods ^goods/(?P<goodid>(\d+))>], [<RegexURLPattern webbrowser webbrowser/>], [<RegexURLResolver <module 'financial.urls' from '/Users/VANXV/PycharmProjects/zss/financial/urls.py'> (None:financialurl) ^financial/>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'servers.urls' from '/Users/VANXV/PycharmProjects/zss/servers/urls.py'> (None:None) ^servers/>], [<RegexURLPattern None ^media\/(?P<path>.*)$>]], 'path': 'users/assets/img/sidebar-1.jpg'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'finance.urls' from '/Users/VANXV/PycharmProjects/zss/finance/urls.py'> (None:finance) ^finance/>"
2017-07-06 00:01:41,110 [Thread-15:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <module 'grappelli.urls' from '/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/grappelli/urls.py'> (None:None) ^grappelli/>], [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'blacklist.urls' from '/Users/VANXV/PycharmProjects/zss/blacklist/urls.py'> (None:blacklist) ^blacklist/>], [<RegexURLResolver <module 'goods.urls' from '/Users/VANXV/PycharmProjects/zss/goods/urls.py'> (None:good) ^good/>], [<RegexURLResolver <module 'orders.urls' from '/Users/VANXV/PycharmProjects/zss/orders/urls.py'> (None:order) ^order/>], [<RegexURLResolver <module 'crm.urls' from '/Users/VANXV/PycharmProjects/zss/crm/urls.py'> (None:crm) ^crm/>], [<RegexURLResolver <module 'finance.urls' from '/Users/VANXV/PycharmProjects/zss/finance/urls.py'> (None:finance) ^finance/>], [<RegexURLResolver <module 'cashback.urls' from '/Users/VANXV/PycharmProjects/zss/cashback/urls.py'> (None:cashback) ^cashback/>], [<RegexURLResolver <module 'cryapp.urls' from '/Users/VANXV/PycharmProjects/zss/cryapp/urls.py'> (None:cryapp) ^cryapp/>], [<RegexURLResolver <module 'wechat.urls' from '/Users/VANXV/PycharmProjects/zss/wechat/urls.py'> (None:wechat) m/>], [<RegexURLPattern login ^login/>], [<RegexURLPattern register ^register/>], [<RegexURLPattern logout ^logout/>], [<RegexURLPattern welcome ^welcome/$>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern PcHardwareInsert ^PcHardwareInsert/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ip ^ip/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^tb/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^jd/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/hardware/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdone ^manage/get/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statussix/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statusseven/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdelete ^manage/delete/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersedit ^manage/edit/(?P<cryorders_id>\d+)/$>], [<RegexURLPattern GetGoods ^goods/(?P<goodid>(\d+))>], [<RegexURLPattern webbrowser webbrowser/>], [<RegexURLResolver <module 'financial.urls' from '/Users/VANXV/PycharmProjects/zss/financial/urls.py'> (None:financialurl) ^financial/>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'servers.urls' from '/Users/VANXV/PycharmProjects/zss/servers/urls.py'> (None:None) ^servers/>], [<RegexURLPattern None ^media\/(?P<path>.*)$>]], 'path': 'users/assets/img/sidebar-1.jpg'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'cashback.urls' from '/Users/VANXV/PycharmProjects/zss/cashback/urls.py'> (None:cashback) ^cashback/>"
2017-07-06 00:01:41,117 [Thread-15:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <module 'grappelli.urls' from '/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/grappelli/urls.py'> (None:None) ^grappelli/>], [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'blacklist.urls' from '/Users/VANXV/PycharmProjects/zss/blacklist/urls.py'> (None:blacklist) ^blacklist/>], [<RegexURLResolver <module 'goods.urls' from '/Users/VANXV/PycharmProjects/zss/goods/urls.py'> (None:good) ^good/>], [<RegexURLResolver <module 'orders.urls' from '/Users/VANXV/PycharmProjects/zss/orders/urls.py'> (None:order) ^order/>], [<RegexURLResolver <module 'crm.urls' from '/Users/VANXV/PycharmProjects/zss/crm/urls.py'> (None:crm) ^crm/>], [<RegexURLResolver <module 'finance.urls' from '/Users/VANXV/PycharmProjects/zss/finance/urls.py'> (None:finance) ^finance/>], [<RegexURLResolver <module 'cashback.urls' from '/Users/VANXV/PycharmProjects/zss/cashback/urls.py'> (None:cashback) ^cashback/>], [<RegexURLResolver <module 'cryapp.urls' from '/Users/VANXV/PycharmProjects/zss/cryapp/urls.py'> (None:cryapp) ^cryapp/>], [<RegexURLResolver <module 'wechat.urls' from '/Users/VANXV/PycharmProjects/zss/wechat/urls.py'> (None:wechat) m/>], [<RegexURLPattern login ^login/>], [<RegexURLPattern register ^register/>], [<RegexURLPattern logout ^logout/>], [<RegexURLPattern welcome ^welcome/$>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern PcHardwareInsert ^PcHardwareInsert/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ip ^ip/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^tb/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^jd/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/hardware/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdone ^manage/get/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statussix/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statusseven/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdelete ^manage/delete/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersedit ^manage/edit/(?P<cryorders_id>\d+)/$>], [<RegexURLPattern GetGoods ^goods/(?P<goodid>(\d+))>], [<RegexURLPattern webbrowser webbrowser/>], [<RegexURLResolver <module 'financial.urls' from '/Users/VANXV/PycharmProjects/zss/financial/urls.py'> (None:financialurl) ^financial/>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'servers.urls' from '/Users/VANXV/PycharmProjects/zss/servers/urls.py'> (None:None) ^servers/>], [<RegexURLPattern None ^media\/(?P<path>.*)$>]], 'path': 'users/assets/img/sidebar-1.jpg'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'cryapp.urls' from '/Users/VANXV/PycharmProjects/zss/cryapp/urls.py'> (None:cryapp) ^cryapp/>"
2017-07-06 00:01:41,120 [Thread-15:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <module 'grappelli.urls' from '/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/grappelli/urls.py'> (None:None) ^grappelli/>], [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'blacklist.urls' from '/Users/VANXV/PycharmProjects/zss/blacklist/urls.py'> (None:blacklist) ^blacklist/>], [<RegexURLResolver <module 'goods.urls' from '/Users/VANXV/PycharmProjects/zss/goods/urls.py'> (None:good) ^good/>], [<RegexURLResolver <module 'orders.urls' from '/Users/VANXV/PycharmProjects/zss/orders/urls.py'> (None:order) ^order/>], [<RegexURLResolver <module 'crm.urls' from '/Users/VANXV/PycharmProjects/zss/crm/urls.py'> (None:crm) ^crm/>], [<RegexURLResolver <module 'finance.urls' from '/Users/VANXV/PycharmProjects/zss/finance/urls.py'> (None:finance) ^finance/>], [<RegexURLResolver <module 'cashback.urls' from '/Users/VANXV/PycharmProjects/zss/cashback/urls.py'> (None:cashback) ^cashback/>], [<RegexURLResolver <module 'cryapp.urls' from '/Users/VANXV/PycharmProjects/zss/cryapp/urls.py'> (None:cryapp) ^cryapp/>], [<RegexURLResolver <module 'wechat.urls' from '/Users/VANXV/PycharmProjects/zss/wechat/urls.py'> (None:wechat) m/>], [<RegexURLPattern login ^login/>], [<RegexURLPattern register ^register/>], [<RegexURLPattern logout ^logout/>], [<RegexURLPattern welcome ^welcome/$>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern PcHardwareInsert ^PcHardwareInsert/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ip ^ip/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^tb/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^jd/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/hardware/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdone ^manage/get/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statussix/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statusseven/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdelete ^manage/delete/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersedit ^manage/edit/(?P<cryorders_id>\d+)/$>], [<RegexURLPattern GetGoods ^goods/(?P<goodid>(\d+))>], [<RegexURLPattern webbrowser webbrowser/>], [<RegexURLResolver <module 'financial.urls' from '/Users/VANXV/PycharmProjects/zss/financial/urls.py'> (None:financialurl) ^financial/>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'servers.urls' from '/Users/VANXV/PycharmProjects/zss/servers/urls.py'> (None:None) ^servers/>], [<RegexURLPattern None ^media\/(?P<path>.*)$>]], 'path': 'users/assets/img/sidebar-1.jpg'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'wechat.urls' from '/Users/VANXV/PycharmProjects/zss/wechat/urls.py'> (None:wechat) m/>"
2017-07-06 00:01:41,169 [Thread-15:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <module 'grappelli.urls' from '/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/grappelli/urls.py'> (None:None) ^grappelli/>], [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'blacklist.urls' from '/Users/VANXV/PycharmProjects/zss/blacklist/urls.py'> (None:blacklist) ^blacklist/>], [<RegexURLResolver <module 'goods.urls' from '/Users/VANXV/PycharmProjects/zss/goods/urls.py'> (None:good) ^good/>], [<RegexURLResolver <module 'orders.urls' from '/Users/VANXV/PycharmProjects/zss/orders/urls.py'> (None:order) ^order/>], [<RegexURLResolver <module 'crm.urls' from '/Users/VANXV/PycharmProjects/zss/crm/urls.py'> (None:crm) ^crm/>], [<RegexURLResolver <module 'finance.urls' from '/Users/VANXV/PycharmProjects/zss/finance/urls.py'> (None:finance) ^finance/>], [<RegexURLResolver <module 'cashback.urls' from '/Users/VANXV/PycharmProjects/zss/cashback/urls.py'> (None:cashback) ^cashback/>], [<RegexURLResolver <module 'cryapp.urls' from '/Users/VANXV/PycharmProjects/zss/cryapp/urls.py'> (None:cryapp) ^cryapp/>], [<RegexURLResolver <module 'wechat.urls' from '/Users/VANXV/PycharmProjects/zss/wechat/urls.py'> (None:wechat) m/>], [<RegexURLPattern login ^login/>], [<RegexURLPattern register ^register/>], [<RegexURLPattern logout ^logout/>], [<RegexURLPattern welcome ^welcome/$>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern PcHardwareInsert ^PcHardwareInsert/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ip ^ip/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^tb/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^jd/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/hardware/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdone ^manage/get/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statussix/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statusseven/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdelete ^manage/delete/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersedit ^manage/edit/(?P<cryorders_id>\d+)/$>], [<RegexURLPattern GetGoods ^goods/(?P<goodid>(\d+))>], [<RegexURLPattern webbrowser webbrowser/>], [<RegexURLResolver <module 'financial.urls' from '/Users/VANXV/PycharmProjects/zss/financial/urls.py'> (None:financialurl) ^financial/>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'servers.urls' from '/Users/VANXV/PycharmProjects/zss/servers/urls.py'> (None:None) ^servers/>], [<RegexURLPattern None ^media\/(?P<path>.*)$>]], 'path': 'users/assets/img/sidebar-1.jpg'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'financial.urls' from '/Users/VANXV/PycharmProjects/zss/financial/urls.py'> (None:financialurl) ^financial/>"
2017-07-06 00:01:41,181 [Thread-15:123145440067584] [django.template:929] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <module 'grappelli.urls' from '/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/grappelli/urls.py'> (None:None) ^grappelli/>], [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'blacklist.urls' from '/Users/VANXV/PycharmProjects/zss/blacklist/urls.py'> (None:blacklist) ^blacklist/>], [<RegexURLResolver <module 'goods.urls' from '/Users/VANXV/PycharmProjects/zss/goods/urls.py'> (None:good) ^good/>], [<RegexURLResolver <module 'orders.urls' from '/Users/VANXV/PycharmProjects/zss/orders/urls.py'> (None:order) ^order/>], [<RegexURLResolver <module 'crm.urls' from '/Users/VANXV/PycharmProjects/zss/crm/urls.py'> (None:crm) ^crm/>], [<RegexURLResolver <module 'finance.urls' from '/Users/VANXV/PycharmProjects/zss/finance/urls.py'> (None:finance) ^finance/>], [<RegexURLResolver <module 'cashback.urls' from '/Users/VANXV/PycharmProjects/zss/cashback/urls.py'> (None:cashback) ^cashback/>], [<RegexURLResolver <module 'cryapp.urls' from '/Users/VANXV/PycharmProjects/zss/cryapp/urls.py'> (None:cryapp) ^cryapp/>], [<RegexURLResolver <module 'wechat.urls' from '/Users/VANXV/PycharmProjects/zss/wechat/urls.py'> (None:wechat) m/>], [<RegexURLPattern login ^login/>], [<RegexURLPattern register ^register/>], [<RegexURLPattern logout ^logout/>], [<RegexURLPattern welcome ^welcome/$>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern PcHardwareInsert ^PcHardwareInsert/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ip ^ip/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^tb/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^jd/>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/hardware/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdone ^manage/get/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statussix/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern None ^manage/statusseven/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersdelete ^manage/delete/(?P<cryorders_id>\d+)/$>], [<RegexURLResolver <module 'users.urls' from '/Users/VANXV/PycharmProjects/zss/users/urls.py'> (None:None) ^users/>, <RegexURLPattern ordersedit ^manage/edit/(?P<cryorders_id>\d+)/$>], [<RegexURLPattern GetGoods ^goods/(?P<goodid>(\d+))>], [<RegexURLPattern webbrowser webbrowser/>], [<RegexURLResolver <module 'financial.urls' from '/Users/VANXV/PycharmProjects/zss/financial/urls.py'> (None:financialurl) ^financial/>], [<RegexURLPattern buyerindex ^$>], [<RegexURLResolver <module 'servers.urls' from '/Users/VANXV/PycharmProjects/zss/servers/urls.py'> (None:None) ^servers/>], [<RegexURLPattern None ^media\/(?P<path>.*)$>]], 'path': 'users/assets/img/sidebar-1.jpg'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/VANXV/PycharmProjects/venvDjango1.11py3.6/lib/python3.6/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'servers.urls' from '/Users/VANXV/PycharmProjects/zss/servers/urls.py'> (None:None) ^servers/>"
2017-07-06 00:01:41,192 [Thread-15:123145440067584] [django.server:131] [basehttp:log_message] [WARNING]- "GET /users/assets/img/sidebar-1.jpg HTTP/1.1" 404 6338
